# Generated by Django 3.0.7 on 2020-08-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('calories', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cal_limit',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='fname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='meals',
            field=models.ManyToManyField(related_name='Eater', to='foodom.Food'),
        ),
    ]
